# Numpy : Numerical Python

- *library* - collection of collections
- why? - functions are resuable and optimized

In [1]:
# Importing libraries
import numpy as np

In [2]:
 np.__version__

'1.23.5'

**why numpy**

- mathematical equation
- faster because built in c++

In [5]:
# list - collection of heterogeneous elements
l = [1,2,3,4,5]

In [6]:
arr = np.array(l)

In [7]:
arr

array([1, 2, 3, 4, 5])

In [9]:
type(arr)

# ndarray - n dimensional array
# ndarray - it stores the same type of data

numpy.ndarray

In [10]:
arr.ndim

1

In [11]:
l2 = [1,2,4,5, 'prasad']

arr2 = np.array(l2)

In [13]:
arr2
## We have one string in the input, but result is converted all elements into strings

array(['1', '2', '4', '5', 'prasad'], dtype='<U21')

In [16]:
arr3 = np.array([[1,2,3,], [4,5,6]])

In [17]:
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
arr3.ndim

2

In [20]:
l3 = [10,20,30,40]

In [25]:
mat = np.matrix(l3)   # always matrics is 2d

In [26]:
mat

matrix([[10, 20, 30, 40]])

In [23]:
## instead of np.array previsouly np.asarray
np.asarray([1,3,4])

array([1, 3, 4])

In [24]:
## alternative method to create array
np.asanyarray([[[(1,2), (3,4)]]])

array([[[[1, 2],
         [3, 4]]]])

In [28]:
np.asanyarray(mat) # mat is already subclass array so it wont convert to nd array again

matrix([[10, 20, 30, 40]])

In [34]:
## shallow copy

arr4 = np.array([1,2,3])
arr5 = arr4

In [36]:
arr5[0] = 1000

In [38]:
arr5

array([1000,    2,    3])

In [39]:
arr4

array([1000,    2,    3])

In [41]:
## Deep copy 

arr6 = np.array([10,20,30])

arr7 = arr6.copy()

In [42]:
arr6[2] = 5000

In [43]:
arr6

array([  10,   20, 5000])

In [44]:
arr7

array([10, 20, 30])

In [49]:
## fromfunction

func = np.fromfunction(lambda i,j: i==j, shape=(3,3))

In [50]:
func.shape

(3, 3)

In [51]:
func.ndim

2

In [52]:
func

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [54]:
func.size

9

In [58]:
## fromiter
iterable = range(5)
it = np.fromiter(iterable, float)
it

array([0., 1., 2., 3., 4.])

In [59]:
# fromstring
np.fromstring("23 34 67", sep=" ")

array([23., 34., 67.])

In [60]:
np.fromstring("1;1;1;1;1", sep=";")

array([1., 1., 1., 1., 1.])

In [61]:
# arange
np.arange(0.1, 3.6, 0.2)

array([0.1, 0.3, 0.5, 0.7, 0.9, 1.1, 1.3, 1.5, 1.7, 1.9, 2.1, 2.3, 2.5,
       2.7, 2.9, 3.1, 3.3, 3.5])

In [66]:
# linspace
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [67]:
# logspace
np.logspace(1,5, 10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [68]:
# zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [70]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [75]:
np.zeros((2,2,1))

array([[[0.],
        [0.]],

       [[0.],
        [0.]]])

In [78]:
np.zeros((2, 2,2,1))

array([[[[0.],
         [0.]],

        [[0.],
         [0.]]],


       [[[0.],
         [0.]],

        [[0.],
         [0.]]]])

In [79]:
# ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [80]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [81]:
arr = np.ones((2,2))

In [82]:
arr + 5

array([[6., 6.],
       [6., 6.]])

In [83]:
arr * 2

array([[2., 2.],
       [2., 2.]])

In [84]:
arr - 1

array([[0., 0.],
       [0., 0.]])

In [85]:
arr / 2

array([[0.5, 0.5],
       [0.5, 0.5]])

## Interview Questions

- what is numpy ?
- array
- list vs array
- why array is faster than list ?
    - list elements are stored the locations of the elements not actually elements. it means list using the references
    - in list, when do append it will create a copt=y of original with new elements, so its use more memory
    - But, in array the size is static and same data type. so its faster, its support vectorization
    