In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [3]:
np.array(l)

array([1, 2, 3, 4])

In [4]:
arr = np.array(l)

In [5]:
type(arr)

numpy.ndarray

In [6]:
np.asarray(l)

array([1, 2, 3, 4])

In [8]:
arr1 = np.array([[1,2,3], [1,2,3]])

In [10]:
arr.ndim

1

In [11]:
arr1.ndim

2

In [13]:
mat =np.matrix(l)

In [14]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4]])

In [15]:
arr

array([1, 2, 3, 4])

In [16]:
a = arr

In [17]:
a

array([1, 2, 3, 4])

In [18]:
arr[0] = 100

In [19]:
arr

array([100,   2,   3,   4])

In [20]:
a

array([100,   2,   3,   4])

In [21]:
b = np.copy(arr)

In [22]:
b[0] = 234

In [23]:
b

array([234,   2,   3,   4])

In [24]:
arr

array([100,   2,   3,   4])

In [25]:
np.fromfunction(lambda i,j: i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [26]:
np.fromfunction(lambda i,j: i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [29]:
list((i*i for i in range(0,5)))

[0, 1, 4, 9, 16]

In [30]:
iterable = (i*i for i in range(5))

In [31]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [32]:
np.fromstring("23 45 35", sep=" ")

array([23., 45., 35.])

In [33]:
np.fromstring("23,45,35", sep=",")

array([23., 45., 35.])

In [34]:
arr

array([100,   2,   3,   4])

In [35]:
arr1

array([[1, 2, 3],
       [1, 2, 3]])

In [36]:
arr.ndim

1

In [37]:
arr.size

4

In [38]:
arr1.size

6

In [39]:
arr.shape

(4,)

In [40]:
arr1.shape

(2, 3)

In [41]:
arr.dtype

dtype('int64')

In [42]:
arr1.dtype

dtype('int64')

In [43]:
# l2

In [44]:
range(0,5)

range(0, 5)

In [45]:
list(range(5))

[0, 1, 2, 3, 4]

In [47]:
list(range(0.2, 5.3))

TypeError: 'float' object cannot be interpreted as an integer

In [48]:
np.arange(2.5, 35.5, 0.5)

array([ 2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,  7.5,
        8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5, 12. , 12.5, 13. ,
       13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5,
       19. , 19.5, 20. , 20.5, 21. , 21.5, 22. , 22.5, 23. , 23.5, 24. ,
       24.5, 25. , 25.5, 26. , 26.5, 27. , 27.5, 28. , 28.5, 29. , 29.5,
       30. , 30.5, 31. , 31.5, 32. , 32.5, 33. , 33.5, 34. , 34.5, 35. ])

In [50]:
np.linspace(1, 5, 20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [51]:
np.logspace(1, 5, 5, base = 2)

array([ 2.,  4.,  8., 16., 32.])

In [53]:
np.zeros(3)

array([0., 0., 0.])

In [54]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [56]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [57]:
np.zeros((2, 3,4,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [59]:
np.ones(4)

array([1., 1., 1., 1.])

In [61]:
arr = np.ones((3,4))

In [62]:
arr + 4

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [63]:
arr - 4

array([[-3., -3., -3., -3.],
       [-3., -3., -3., -3.],
       [-3., -3., -3., -3.]])

In [64]:
arr *4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [66]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [68]:
arr3 = np.eye(5)

In [69]:
arr3

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [70]:
import pandas as pd

In [71]:
pd.DataFrame(arr3)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [72]:
np.random.rand(2, 3)

array([[0.07779472, 0.5128444 , 0.54905347],
       [0.97244659, 0.3762963 , 0.76675791]])

In [74]:
np.random.randn(2,3)

array([[ 0.3555414 ,  0.45955392, -1.78258304],
       [ 0.53506836,  0.36038696,  0.58545233]])

In [77]:
arr4 = np.random.randint(1, 5, (3, 4))

In [78]:
arr4

array([[2, 3, 3, 3],
       [2, 3, 4, 3],
       [1, 3, 1, 3]])

In [79]:
arr4.shape

(3, 4)

In [80]:
arr4.reshape(6, 2)

array([[2, 3],
       [3, 3],
       [2, 3],
       [4, 3],
       [1, 3],
       [1, 3]])

In [81]:
arr4

array([[2, 3, 3, 3],
       [2, 3, 4, 3],
       [1, 3, 1, 3]])

In [82]:
arr4.reshape(5,5)

ValueError: cannot reshape array of size 12 into shape (5,5)

In [84]:
arr4.reshape(4,-2342)

array([[2, 3, 3],
       [3, 2, 3],
       [4, 3, 1],
       [3, 1, 3]])

In [85]:
arr4.reshape(4,-1)

array([[2, 3, 3],
       [3, 2, 3],
       [4, 3, 1],
       [3, 1, 3]])

In [86]:
arr4.reshape(2,3,2)

array([[[2, 3],
        [3, 3],
        [2, 3]],

       [[4, 3],
        [1, 3],
        [1, 3]]])

In [87]:
arr5 = np.random.randint(1, 10, (5,5))

In [88]:
arr5 > 8

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [89]:
arr5[arr5>8]

array([9])

In [90]:
arr5

array([[2, 6, 7, 8, 8],
       [7, 6, 3, 5, 7],
       [9, 6, 1, 8, 2],
       [1, 4, 2, 8, 4],
       [4, 5, 8, 6, 5]])

In [91]:
arr5[0]

array([2, 6, 7, 8, 8])

In [92]:
arr[0, [0,1]]

array([1., 1.])

In [93]:
arr5[2:4, [2,4]]

array([[1, 2],
       [2, 4]])

In [94]:
arr5[2:4, 2:4]

array([[1, 8],
       [2, 8]])

In [95]:
arr6 = np.random.randint(1, 3, (3,3))
arr7 = np.random.randint(1, 3, (3,3))

In [96]:
arr6

array([[2, 1, 2],
       [2, 1, 2],
       [2, 2, 1]])

In [97]:
arr7

array([[1, 1, 2],
       [1, 1, 2],
       [2, 2, 2]])

In [98]:
arr6  + arr7

array([[3, 2, 4],
       [3, 2, 4],
       [4, 4, 3]])

In [99]:
arr6 - arr7

array([[ 1,  0,  0],
       [ 1,  0,  0],
       [ 0,  0, -1]])

In [100]:
arr6 * arr7

array([[2, 1, 4],
       [2, 1, 4],
       [4, 4, 2]])

In [101]:
arr6@arr7

array([[ 7,  7, 10],
       [ 7,  7, 10],
       [ 6,  6, 10]])

In [102]:
arr6 / arr7

array([[2. , 1. , 1. ],
       [2. , 1. , 1. ],
       [1. , 1. , 0.5]])

In [103]:
arr6/0

/tmp/ipykernel_7502/1351048935.py:1: RuntimeWarning: divide by zero encountered in divide
  arr6/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [104]:
# numpy broadcasting

In [106]:
arr = np.zeros((3, 4))

In [107]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [108]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [116]:
a = np.array([[1,2,3,4]])

In [117]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [122]:
b = np.array([[3,4,5]])

In [123]:
arr + b

ValueError: operands could not be broadcast together with shapes (3,4) (1,3) 

In [124]:
b.T

array([[3],
       [4],
       [5]])

In [125]:
arr + b.T

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [127]:
## sqrt

np.sqrt(arr6)

array([[1.41421356, 1.        , 1.41421356],
       [1.41421356, 1.        , 1.41421356],
       [1.41421356, 1.41421356, 1.        ]])

In [128]:
np.log10(arr6)

array([[0.30103, 0.     , 0.30103],
       [0.30103, 0.     , 0.30103],
       [0.30103, 0.30103, 0.     ]])

In [129]:
np.exp(arr7)

array([[2.71828183, 2.71828183, 7.3890561 ],
       [2.71828183, 2.71828183, 7.3890561 ],
       [7.3890561 , 7.3890561 , 7.3890561 ]])

In [130]:
np.min(arr6)

1

In [131]:
np.max(arr7)

2

In [136]:
# l3
import numpy as np

In [137]:
arr = np.random.randint(1, 10, (4,4))

In [138]:
arr

array([[5, 8, 1, 1],
       [3, 2, 9, 2],
       [1, 1, 3, 6],
       [8, 6, 1, 6]])

In [139]:
arr.T

array([[5, 3, 1, 8],
       [8, 2, 1, 6],
       [1, 9, 3, 1],
       [1, 2, 6, 6]])

In [140]:
arr.flatten()

array([5, 8, 1, 1, 3, 2, 9, 2, 1, 1, 3, 6, 8, 6, 1, 6])

In [141]:
arr

array([[5, 8, 1, 1],
       [3, 2, 9, 2],
       [1, 1, 3, 6],
       [8, 6, 1, 6]])

In [144]:
arr1 =np.expand_dims(arr, axis=1)

In [145]:
arr.ndim

2

In [146]:
arr1.ndim

3

In [147]:
arr2 =np.expand_dims(arr, axis=0)

In [148]:
arr2.ndim

3

In [149]:
arr2

array([[[5, 8, 1, 1],
        [3, 2, 9, 2],
        [1, 1, 3, 6],
        [8, 6, 1, 6]]])

In [150]:
arr1

array([[[5, 8, 1, 1]],

       [[3, 2, 9, 2]],

       [[1, 1, 3, 6]],

       [[8, 6, 1, 6]]])

In [151]:
data = np.array([[1], [2], [3]])

In [153]:
np.squeeze(data)

array([1, 2, 3])

In [154]:
np.repeat(data, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [156]:
np.roll(data, 2)

array([[2],
       [3],
       [1]])

In [157]:
np.diag(np.array([1,2,3]))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [158]:
arr1 =np.random.randint(1, 10, (3,4))

In [159]:
arr2 = np.random.randint(1,5, (3,4))

In [160]:
arr1**arr2

array([[6561,    3,   25,    9],
       [   1,    1,    7,   64],
       [ 343,  625,  216, 2401]])

In [161]:
~arr1

array([[-10,  -4,  -6, -10],
       [ -2,  -2,  -8,  -5],
       [ -8,  -6,  -7,  -8]])

In [163]:
arr1 > arr2

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [164]:
## string operation

arr = np.array(['pras', 'nadi', 'sao'])

In [166]:
np.char.upper(arr)

array(['PRAS', 'NADI', 'SAO'], dtype='<U4')

In [167]:
np.char.capitalize(arr)

array(['Pras', 'Nadi', 'Sao'], dtype='<U4')

In [168]:
## Mathematica

In [170]:
np.sin(arr6)

array([[0.90929743, 0.84147098, 0.90929743],
       [0.90929743, 0.84147098, 0.90929743],
       [0.90929743, 0.90929743, 0.84147098]])

In [171]:
np.tan(arr7)

array([[ 1.55740772,  1.55740772, -2.18503986],
       [ 1.55740772,  1.55740772, -2.18503986],
       [-2.18503986, -2.18503986, -2.18503986]])

In [172]:
np.log10(arr5)

array([[0.30103   , 0.77815125, 0.84509804, 0.90308999, 0.90308999],
       [0.84509804, 0.77815125, 0.47712125, 0.69897   , 0.84509804],
       [0.95424251, 0.77815125, 0.        , 0.90308999, 0.30103   ],
       [0.        , 0.60205999, 0.30103   , 0.90308999, 0.60205999],
       [0.60205999, 0.69897   , 0.90308999, 0.77815125, 0.69897   ]])

In [174]:
np.exp(arr5)

array([[7.38905610e+00, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        2.98095799e+03],
       [1.09663316e+03, 4.03428793e+02, 2.00855369e+01, 1.48413159e+02,
        1.09663316e+03],
       [8.10308393e+03, 4.03428793e+02, 2.71828183e+00, 2.98095799e+03,
        7.38905610e+00],
       [2.71828183e+00, 5.45981500e+01, 7.38905610e+00, 2.98095799e+03,
        5.45981500e+01],
       [5.45981500e+01, 1.48413159e+02, 2.98095799e+03, 4.03428793e+02,
        1.48413159e+02]])

In [177]:
np.power(arr5, 2)

array([[ 4, 36, 49, 64, 64],
       [49, 36,  9, 25, 49],
       [81, 36,  1, 64,  4],
       [ 1, 16,  4, 64, 16],
       [16, 25, 64, 36, 25]])

In [179]:
np.mean(arr1)

5.333333333333333

In [180]:
np.median(arr1)

5.5

In [181]:
np.var(arr1)

6.722222222222221

In [183]:
np.std(arr1)

2.592724864350674

In [184]:
np.min(arr1)

1

In [185]:
np.max(arr1)

9

In [186]:
arr

array(['pras', 'nadi', 'sao'], dtype='<U4')

In [187]:
arr6

array([[2, 1, 2],
       [2, 1, 2],
       [2, 2, 1]])

In [188]:
arr7

array([[1, 1, 2],
       [1, 1, 2],
       [2, 2, 2]])

In [189]:
np.multiply(arr6, arr7)

array([[2, 1, 4],
       [2, 1, 4],
       [4, 4, 2]])

In [190]:
np.subtract(arr6, arr7)

array([[ 1,  0,  0],
       [ 1,  0,  0],
       [ 0,  0, -1]])

In [191]:
# l4

In [192]:
# sort, search, count

In [193]:
import numpy as np

In [194]:
np.array([2,3,4,5])

array([2, 3, 4, 5])

In [196]:
a = np.array([51, 61, 2, 4, 13, 52])

In [197]:
np.sort(a)

array([ 2,  4, 13, 51, 52, 61])

In [198]:
np.searchsorted(a, 61)

6

In [200]:
arr1 = np.array([0, 2342, 253, 0, 23, 234, 0])

In [203]:
np.count_nonzero(arr1)

4

In [204]:
np.where(arr1>0)

(array([1, 2, 4, 5]),)

In [205]:
np.extract(arr1>2, arr1)

array([2342,  253,   23,  234])

In [206]:
##  Byte swapping

In [207]:
arr1

array([   0, 2342,  253,    0,   23,  234,    0])

In [208]:
arr1.byteswap()

array([                   0,  2740721848231657472,  -216172782113783808,
                          0,  1657324662872342528, -1585267068834414592,
                          0])

In [209]:
## Deep copy and shallown copy

In [210]:
## view

b = arr1.view()

In [211]:
arr1

array([   0, 2342,  253,    0,   23,  234,    0])

In [212]:
b

array([   0, 2342,  253,    0,   23,  234,    0])

In [213]:
b[0]= 10000

In [214]:
b

array([10000,  2342,   253,     0,    23,   234,     0])

In [215]:
arr1

array([10000,  2342,   253,     0,    23,   234,     0])

In [216]:
## Matrix

In [217]:
import numpy.matlib as nm

In [218]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [219]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [221]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [222]:
## linear algreda

arr2 = np.random.randint(1, 5, (2,2))
arr3 = np.random.randint(3, 5, (2,5))

In [224]:
arr2

array([[3, 1],
       [4, 2]])

In [225]:
arr3

array([[4, 3, 4, 4, 4],
       [4, 3, 3, 4, 3]])

In [223]:
np.dot(arr2, arr3)

array([[16, 12, 15, 16, 15],
       [24, 18, 22, 24, 22]])