# Numpy

- numpy: Numerical Python
- library contains 1000+ function which are resuable and optimized.
- numpy array means collection of same type elements. 
- numpy arrays are faster because this build on c++

In [2]:
# Importing the library
import numpy as np

## Create numpy array

- `np.array()` and `np.asarry()` both are used to create the numpy arrays.
- we can create numpy arrays from lists and typles

In [4]:
# 1. np.array()

l = [10,20,30,40]
arr1 = np.array(l)
arr1

array([10, 20, 30, 40])

In [5]:
l2 = [[1,2,3], [2,2,2]]
arr2 = np.array(l2)
arr2

array([[1, 2, 3],
       [2, 2, 2]])

In [7]:
arr3 = np.array([1,5, 10])
arr3

array([ 1,  5, 10])

In [11]:
# 2. np.asarray()

arr4 = np.asarray((1,2,3,4,5,5,5,5,5))
arr4

array([1, 2, 3, 4, 5, 5, 5, 5, 5])

## characteristics
- ndim - returns the dimension of the array
- shape - returns the number of rows and columns
- size - returns total number of elements in the array.
- dtype - returns the data type of the array

In [17]:
# 3. arr.ndim
arr1.ndim

1

In [18]:
arr2.ndim

2

In [19]:
arr3.ndim

1

In [20]:
# 4. shape
arr1.shape

(4,)

In [21]:
arr2.shape

(2, 3)

In [22]:
## 5. size
arr1.size

4

In [23]:
arr2.size

6

In [24]:
## 6. dtype
arr1.dtype

dtype('int64')

In [25]:
arr2.dtype

dtype('int64')

`np.matrix()` - It create a matrix. The size of the matrix is always 2-dimensional. It will through error if dimension greather than 2. 
- if we give one dimensional array, during matrix creation the dimension is changed to 2.

In [27]:

mat = np.matrix([1,2,3,4])
mat

matrix([[1, 2, 3, 4]])

In [28]:
arr = [[[1,2,3], [1,2,3], [1,2,3]]]
mat2 = np.matrix(arr)

ValueError: matrix must be 2-dimensional

In [29]:
arr = [[10,202, 20], [2, 4, 6]]
mat3 = np.matrix(arr)
mat3

matrix([[ 10, 202,  20],
        [  2,   4,   6]])

**Shallow copy**

In [30]:
a = np.array([100, 200, 300, 400])

In [31]:
b = a

In [32]:
#update any value in a or b, it effects the changes is parallely
a[0] = 1

In [33]:
a

array([  1, 200, 300, 400])

In [34]:
b

array([  1, 200, 300, 400])

**Deep copy**

In [35]:
arr = np.array([5, 10, 25, 35])

In [36]:
arrCopy = arr.copy()

In [37]:
arr[1] = 10000000

In [38]:
arr

array([       5, 10000000,       25,       35])

In [39]:
arrCopy

array([ 5, 10, 25, 35])

**fromfunction** - It generates array by using the defined function

In [40]:
np.fromfunction(lambda i, j: i==j, shape=(4,5))

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False]])

In [43]:
np.fromfunction(lambda i, j: i*j, shape=(4,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  2.,  4.,  6.,  8.],
       [ 0.,  3.,  6.,  9., 12.]])

In [48]:
def power(a, b):
    return a**b

np.fromfunction(lambda i, j: power(i, j), shape = (3,3))

array([[1., 0., 0.],
       [1., 1., 1.],
       [1., 2., 4.]])

**fromiter** - generates array from the iterables

In [45]:
iterables = (i*i for i in range(0,5))
np.fromiter(iterables, float)

array([ 0.,  1.,  4.,  9., 16.])

**fromstring** - generate array from the string with common separator


In [56]:
string = "1999,24, 65, 76, 67, 234"
np.fromstring(string, sep=",", dtype=int)

array([1999,   24,   65,   76,   67,  234])

- `range()` in python doesnot support with floating values. 
- `np.arange()` in numpy support floating values as well

In [57]:
range(6.2, 9)

TypeError: 'float' object cannot be interpreted as an integer

In [58]:
np.arange(0.2, 6)

array([0.2, 1.2, 2.2, 3.2, 4.2, 5.2])

**`np.linspcae()` - it will generate array with equal distance elements from low to high for given size**

In [59]:
np.linspace(start=1, stop=10, num=20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

**`np.logspace()` - generate array with log values from start to stop for given num along with log base**

In [60]:
np.logspace(start = 2, stop= 4, num=5, base = 2)

array([ 4.        ,  5.65685425,  8.        , 11.3137085 , 16.        ])

**`np.zeros()` - generate array with zeros of given shape**

In [61]:
np.zeros(4)

array([0., 0., 0., 0.])

In [62]:
np.zeros(shape=(3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [63]:
np.zeros(shape=(4, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

**`np.ones()` - generates array with all ones for given shape**

In [65]:
np.ones(4)

array([1., 1., 1., 1.])

In [66]:
np.ones(shape= (4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**`np.empty()` - generates array with random number for given shape**

In [67]:
np.empty(shape=(6,6))

array([[4.67523793e-310, 0.00000000e+000, 6.93427679e-310,
        6.93427679e-310, 6.93427678e-310, 6.93427679e-310],
       [6.93427679e-310, 6.93427665e-310, 6.93427680e-310,
        6.93427672e-310, 6.93427707e-310, 4.67627317e-310],
       [0.00000000e+000, 0.00000000e+000, 6.93427579e-310,
        6.93427580e-310, 6.93427579e-310, 6.93427615e-310],
       [6.93427579e-310, 6.93427616e-310, 6.93427591e-310,
        6.93427579e-310, 6.93427590e-310, 6.93427590e-310],
       [6.93427591e-310, 6.93427591e-310, 6.93427592e-310,
        6.93427615e-310, 6.93427592e-310, 6.93427592e-310],
       [6.93427592e-310, 6.93427592e-310, 6.93427580e-310,
        6.93427592e-310, 6.93427580e-310, 6.93427592e-310]])

**`np.eye()` - generates identity matrix, here number of rows and columns always eqaul**

In [69]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

**`np.random.rand()` - generate random values for for given shape**

In [71]:
np.random.rand(2,3)

array([[0.68944712, 0.74835961, 0.02486407],
       [0.29070324, 0.60447769, 0.67493839]])

**`np.random.randn()` - generate elements in stadard distrubution in given shape**

In [75]:
np.random.randn(3,3)

array([[ 0.18500356,  1.42043413, -0.29452761],
       [ 0.66351916,  1.81544211,  1.16422108],
       [ 0.38371718, -0.20879405,  0.84950532]])

**`np.random.randint()` - generate integers between low to high with given shape**

In [80]:
arr = np.random.randint(low = 0, high = 35, size=(6,3))
arr

array([[ 4, 32,  6],
       [ 4, 18, 32],
       [ 2, 21,  4],
       [11,  5, 27],
       [15, 25, 26],
       [23, 10, 20]])

**arr.shape()** - reshape to different shape. the result shape should be multiples of input shape

In [81]:
arr.reshape(9,2)

array([[ 4, 32],
       [ 6,  4],
       [18, 32],
       [ 2, 21],
       [ 4, 11],
       [ 5, 27],
       [15, 25],
       [26, 23],
       [10, 20]])

In [82]:
arr.reshape(3,3,2)

array([[[ 4, 32],
        [ 6,  4],
        [18, 32]],

       [[ 2, 21],
        [ 4, 11],
        [ 5, 27]],

       [[15, 25],
        [26, 23],
        [10, 20]]])

**`filter with condition`**

In [83]:
arr

array([[ 4, 32,  6],
       [ 4, 18, 32],
       [ 2, 21,  4],
       [11,  5, 27],
       [15, 25, 26],
       [23, 10, 20]])

In [84]:
arr > 15

array([[False,  True, False],
       [False,  True,  True],
       [False,  True, False],
       [False, False,  True],
       [False,  True,  True],
       [ True, False,  True]])

In [85]:
arr[arr>15]

array([32, 18, 32, 21, 27, 25, 26, 23, 20])

**`slicing` - subselection of rows and columns**

In [86]:
arr

array([[ 4, 32,  6],
       [ 4, 18, 32],
       [ 2, 21,  4],
       [11,  5, 27],
       [15, 25, 26],
       [23, 10, 20]])

In [87]:
arr[0]

array([ 4, 32,  6])

In [88]:
arr[0:3]

array([[ 4, 32,  6],
       [ 4, 18, 32],
       [ 2, 21,  4]])

In [89]:
arr[0:3, 1]

array([32, 18, 21])

In [92]:
arr[0:4, 1:]

array([[32,  6],
       [18, 32],
       [21,  4],
       [ 5, 27]])

**`Index wise arthematic operations` - perfrom addition/subtraction/multiplication index wise**

In [95]:
arr1 = np.random.randint(5, 50, (3,3))
arr2 = np.random.randint(1, 5, (3,3))

In [96]:
arr1

array([[ 7, 42, 18],
       [18, 30, 32],
       [ 5, 13, 14]])

In [97]:
arr2

array([[3, 3, 3],
       [4, 2, 2],
       [2, 1, 2]])

In [98]:
arr1 + arr2

array([[10, 45, 21],
       [22, 32, 34],
       [ 7, 14, 16]])

In [99]:
arr1 - arr2

array([[ 4, 39, 15],
       [14, 28, 30],
       [ 3, 12, 12]])

In [100]:
arr1 * arr2

array([[ 21, 126,  54],
       [ 72,  60,  64],
       [ 10,  13,  28]])

In [101]:
arr1 / arr2

array([[ 2.33333333, 14.        ,  6.        ],
       [ 4.5       , 15.        , 16.        ],
       [ 2.5       , 13.        ,  7.        ]])

In [102]:
arr1 % arr2

array([[1, 0, 0],
       [2, 0, 0],
       [1, 0, 0]])

In [103]:
arr1/0

/tmp/ipykernel_3935/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

**`Matrix multiplication`**

In [105]:
arr1 @ arr2

array([[225, 123, 141],
       [238, 146, 178],
       [ 95,  55,  69]])

**`Broadcasting`**

In [106]:
arr

array([[ 4, 32,  6],
       [ 4, 18, 32],
       [ 2, 21,  4],
       [11,  5, 27],
       [15, 25, 26],
       [23, 10, 20]])

In [107]:
arr + 5

array([[ 9, 37, 11],
       [ 9, 23, 37],
       [ 7, 26,  9],
       [16, 10, 32],
       [20, 30, 31],
       [28, 15, 25]])

In [108]:
arr * 2

array([[ 8, 64, 12],
       [ 8, 36, 64],
       [ 4, 42,  8],
       [22, 10, 54],
       [30, 50, 52],
       [46, 20, 40]])

In [109]:
arr - 2

array([[ 2, 30,  4],
       [ 2, 16, 30],
       [ 0, 19,  2],
       [ 9,  3, 25],
       [13, 23, 24],
       [21,  8, 18]])

In [110]:
a = np.array([[1,1,1]])

In [111]:
arr + a

array([[ 5, 33,  7],
       [ 5, 19, 33],
       [ 3, 22,  5],
       [12,  6, 28],
       [16, 26, 27],
       [24, 11, 21]])

In [115]:
b = np.array([[3,3,3,3,3,3]])

In [116]:
arr + b.T

array([[ 7, 35,  9],
       [ 7, 21, 35],
       [ 5, 24,  7],
       [14,  8, 30],
       [18, 28, 29],
       [26, 13, 23]])

**`Mathematical Equations`**

In [118]:
np.sqrt(arr)

array([[2.        , 5.65685425, 2.44948974],
       [2.        , 4.24264069, 5.65685425],
       [1.41421356, 4.58257569, 2.        ],
       [3.31662479, 2.23606798, 5.19615242],
       [3.87298335, 5.        , 5.09901951],
       [4.79583152, 3.16227766, 4.47213595]])

In [119]:
np.power(arr, 2)

array([[  16, 1024,   36],
       [  16,  324, 1024],
       [   4,  441,   16],
       [ 121,   25,  729],
       [ 225,  625,  676],
       [ 529,  100,  400]])

In [120]:
np.exp(arr)

array([[5.45981500e+01, 7.89629602e+13, 4.03428793e+02],
       [5.45981500e+01, 6.56599691e+07, 7.89629602e+13],
       [7.38905610e+00, 1.31881573e+09, 5.45981500e+01],
       [5.98741417e+04, 1.48413159e+02, 5.32048241e+11],
       [3.26901737e+06, 7.20048993e+10, 1.95729609e+11],
       [9.74480345e+09, 2.20264658e+04, 4.85165195e+08]])

In [121]:
np.log10(arr)

array([[0.60205999, 1.50514998, 0.77815125],
       [0.60205999, 1.25527251, 1.50514998],
       [0.30103   , 1.32221929, 0.60205999],
       [1.04139269, 0.69897   , 1.43136376],
       [1.17609126, 1.39794001, 1.41497335],
       [1.36172784, 1.        , 1.30103   ]])

In [122]:
np.min(arr)

2

In [123]:
np.max(arr)

32

In [125]:
np.median(arr)

16.5

In [126]:
np.sum(arr)

285

In [127]:
np.sum(arr, axis=0)

array([ 59, 111, 115])

In [128]:
np.sum(arr, axis = 1)

array([42, 54, 27, 43, 66, 53])

In [129]:
np.sin(arr)

array([[-0.7568025 ,  0.55142668, -0.2794155 ],
       [-0.7568025 , -0.75098725,  0.55142668],
       [ 0.90929743,  0.83665564, -0.7568025 ],
       [-0.99999021, -0.95892427,  0.95637593],
       [ 0.65028784, -0.13235175,  0.76255845],
       [-0.8462204 , -0.54402111,  0.91294525]])

In [130]:
np.tan(arr)

array([[ 1.15782128e+00,  6.61006041e-01, -2.91006191e-01],
       [ 1.15782128e+00, -1.13731371e+00,  6.61006041e-01],
       [-2.18503986e+00, -1.52749853e+00,  1.15782128e+00],
       [-2.25950846e+02, -3.38051501e+00, -3.27370380e+00],
       [-8.55993401e-01, -1.33526407e-01,  1.17875355e+00],
       [ 1.58815308e+00,  6.48360827e-01,  2.23716094e+00]])

In [131]:
np.var(arr)

101.02777777777777

In [132]:
np.std(arr)

10.051257522209735

In [133]:
np.cov(arr)

array([[ 244.        ,   14.        ,  163.        , -118.        ,
          46.        , -105.        ],
       [  14.        ,  196.        ,   14.        ,  112.        ,
          77.        ,  -21.        ],
       [ 163.        ,   14.        ,  109.        ,  -76.        ,
          32.5       ,  -70.5       ],
       [-118.        ,  112.        ,  -76.        ,  129.33333333,
          23.        ,   41.66666667],
       [  46.        ,   77.        ,   32.5       ,   23.        ,
          37.        ,  -25.5       ],
       [-105.        ,  -21.        ,  -70.5       ,   41.66666667,
         -25.5       ,   46.33333333]])

**`important function`**

In [135]:
arr

array([[ 4, 32,  6],
       [ 4, 18, 32],
       [ 2, 21,  4],
       [11,  5, 27],
       [15, 25, 26],
       [23, 10, 20]])

In [136]:
# convert any shape elements into single array
arr.flatten()

array([ 4, 32,  6,  4, 18, 32,  2, 21,  4, 11,  5, 27, 15, 25, 26, 23, 10,
       20])

In [137]:
arr

array([[ 4, 32,  6],
       [ 4, 18, 32],
       [ 2, 21,  4],
       [11,  5, 27],
       [15, 25, 26],
       [23, 10, 20]])

In [138]:
arr.ndim

2

In [141]:
## Adding extra axis
arr1 = np.expand_dims(arr, axis=0)
arr1

array([[[ 4, 32,  6],
        [ 4, 18, 32],
        [ 2, 21,  4],
        [11,  5, 27],
        [15, 25, 26],
        [23, 10, 20]]])

In [142]:
## Squeeze the data into single array
data = np.array([[1], [2], [3]])
np.squeeze(data)

array([1, 2, 3])

In [144]:
## repeat the array with k times
np.repeat(data, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [155]:
## diagonal 
b = np.diag(np.array([1,2,3,4,5]))
b

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [152]:
# sorting array
a = [9, 5, 2, 7, 2]
np.sort(a)

array([2, 2, 5, 7, 9])

In [156]:
# counting non zero elements
np.count_nonzero(b)

5

In [159]:
# where - apply conditions
np.where(b > 0)

(array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]))

**`string operations`**

In [148]:
arr = np.array(['pras', 'nadi', 'sao'])

In [149]:
np.char.upper(arr)

array(['PRAS', 'NADI', 'SAO'], dtype='<U4')

In [150]:
np.char.capitalize(arr)

array(['Pras', 'Nadi', 'Sao'], dtype='<U4')