In [1]:
import numpy as np

In [2]:
arr = np.ones((3,4))

In [3]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
arr + 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [5]:
arr*2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [6]:
np.empty(shape=(3,2))   # some random of given shape

array([[6.90680739e-310, 4.68988080e-310],
       [2.42869050e-313, 6.18196790e-309],
       [5.75436583e-268, 4.02977162e-270]])

In [7]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
import pandas as pd

pd.DataFrame(arr)

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0

In [12]:
pd.DataFrame(arr, columns=['A', 'B', 'C', 'D'])

A    B    C    D
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0

In [13]:
import random

In [15]:
random.choice([1,2,3,4,5,6])

5

In [17]:
random.randrange(1,1000)

9

In [18]:
random.random()

0.6634013525339757

In [19]:
lis = [1,2,3,4,5]

In [20]:
random.shuffle(lis)

In [22]:
lis

[4, 2, 1, 5, 3]

In [23]:
random.uniform(7, 14)

12.607103220148792

In [24]:
import numpy as np

In [25]:
np.random.rand(2,2)

array([[0.1359856 , 0.47490457],
       [0.06906336, 0.0433818 ]])

In [26]:
np.random.randn(3,4)

array([[-0.65159133,  1.98079147, -1.68701861, -0.59747001],
       [ 0.65760913, -0.79313564,  0.29323215,  0.981511  ],
       [-0.66791299, -0.34031419,  0.15429464, -0.10962704]])

In [27]:
np.random.random_sample()

0.20365776986613815

In [28]:
np.random.randint(1,5, (3,4))

array([[2, 2, 4, 4],
       [3, 3, 1, 4],
       [1, 3, 3, 2]])

In [29]:
arr.size

12

In [30]:
arr.shape

(3, 4)

In [31]:
arr.ndim

2

In [32]:
arr.size

12

In [33]:
arr.reshape(6,2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [36]:
arr.reshape(12,)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
arr.reshape(1,12)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [39]:
arr.reshape(4, -1)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [41]:
arr.reshape(-1, 6)

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [43]:
arr.reshape(2,2,3)

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [44]:
arr.reshape(1,2,2,3)

array([[[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]])

In [45]:
arr > 0

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [48]:
arr[arr <=1]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [49]:
arr = np.random.randint(1, 25, (5,6))

In [50]:
arr

array([[ 6,  3, 11, 14,  4, 17],
       [10,  8,  6, 23,  9,  9],
       [16,  6, 14,  4, 13,  3],
       [19,  5, 17, 13, 24, 12],
       [24, 18, 18, 16, 24, 14]])

In [54]:
arr[0, 2:]

array([11, 14,  4, 17])

In [55]:
## BroadCasting

In [56]:
arr

array([[ 6,  3, 11, 14,  4, 17],
       [10,  8,  6, 23,  9,  9],
       [16,  6, 14,  4, 13,  3],
       [19,  5, 17, 13, 24, 12],
       [24, 18, 18, 16, 24, 14]])

In [57]:
arr + 10

array([[16, 13, 21, 24, 14, 27],
       [20, 18, 16, 33, 19, 19],
       [26, 16, 24, 14, 23, 13],
       [29, 15, 27, 23, 34, 22],
       [34, 28, 28, 26, 34, 24]])

In [59]:
arr - 5

array([[ 1, -2,  6,  9, -1, 12],
       [ 5,  3,  1, 18,  4,  4],
       [11,  1,  9, -1,  8, -2],
       [14,  0, 12,  8, 19,  7],
       [19, 13, 13, 11, 19,  9]])

In [76]:
a = np.array([[1,2,3,4]])

In [77]:
arr + a

ValueError: operands could not be broadcast together with shapes (5,6) (1,4) 

In [78]:
a = np.array([1,2,3,4, 5, 6])

In [79]:
arr + a

array([[ 7,  5, 14, 18,  9, 23],
       [11, 10,  9, 27, 14, 15],
       [17,  8, 17,  8, 18,  9],
       [20,  7, 20, 17, 29, 18],
       [25, 20, 21, 20, 29, 20]])

In [80]:
arr

array([[ 6,  3, 11, 14,  4, 17],
       [10,  8,  6, 23,  9,  9],
       [16,  6, 14,  4, 13,  3],
       [19,  5, 17, 13, 24, 12],
       [24, 18, 18, 16, 24, 14]])

In [81]:
b = np.array([[1,1,1,1,1]])

In [82]:
arr + b.T

array([[ 7,  4, 12, 15,  5, 18],
       [11,  9,  7, 24, 10, 10],
       [17,  7, 15,  5, 14,  4],
       [20,  6, 18, 14, 25, 13],
       [25, 19, 19, 17, 25, 15]])